#!/bin/bash

haefen_init() {
	cd /home
	for usr in ${USER}-*
	do
		xauth list | (while read a ; do XAUTHORITY=/home/${usr}/.Xauthority sudo -u ${usr} xauth add $a ; done )
	done
	cp ${XAUTHORITY} ${XAUTHORITY}.haefen_init
}

diff -q ${XAUTHORITY} ${XAUTHORITY}.haefen_init || haefen_init 

HAEFEN=$1
shift 
if [[ ! ${HAEFEN} ]] 
then
	echo "FAIL: I need at least a jailname and a command"
	echo "Usage: jail HAEFEN CMD ..."
	exit 1
fi
if [[ ! ${@} ]] 
then
	echo "FAIL: I need at least a command to run in the jail named ${HAEFEN}"
	exit 2
fi
XAUTHORITY=/home/${USER}-${HAEFEN}/.Xauthority sudo -u ${USER}-${HAEFEN} $@

